apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_NAME: bWFudXRlbmNhb19kYg==


#apiVersion: v1
#kind: Secret
#metadata:
#  name: app-secret 
#  labels:
#    app: meu-projeto
#type: Opaque
#data:
 # DB_USER: 
 # DB_PASSWORD:
 # DB_NAME:
